### PR TITLE
removing canonicalized paths from manifest

### LINKED ISSUE #143: Manifest Redundancy
# Summary

## Problem

The manifest records the canonical paths of files unnecessarily. Root path + path within the input filesystem should be enough to perform unpack.

### PR DESCRIPTION
**Pull request by laudiacay**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

removed the tons of paths from the manifest file

## Link to issue

Please add a link to any relevant issues/tickets.

#143

## Type of change

- [ ] Bug fix (non-breaking change that fixes an issue)
- [ ] New feature (non-breaking change that adds functionality)
- [ ] Refactor (non-breaking change that updates existing functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update
- [x] Comments have been added/updated

Please delete options that are not relevant.

## Test plan (required)

Demonstrate the code is solid. Which commands did you test with and what are the expected results?
Which tests have you added or updated? Do the tests cover all of the changes included in this PR?

help- needs version bump

## Screenshots/Screencaps

Please add previews of any UI Changes.

### CODE REVIEW

**Comment by laudiacay** [comment]
@organizedgrime this needs a version bump because i edited the manifest. i bumped the version. i think all we need besides this is to tag this commit with 0.2.0 after this, right? i'm ok with breaking semver a little right now...

**Comment by laudiacay** [comment]
bumping @amiller68

**Review by recursivepaws — APPROVED** [review]
Changes look good, this reduced redundancy both in our structs and in our manifest output. Only thing worth noting is that despite breaking backwards compatibility, we've only bumped the minor version from `0.1.0` -> `0.1.1`. @laudiacay you said you're okay with ignoring version compat standards for the moment so let's just run with this. We'll have to bump the version number in a major way once WNFS is integrated so these minor breaking changes are relatively unimportant by contrast.

**Comment by laudiacay** [comment]
thanks !!

**Pull request merged**
